# Generated by Django 3.2.7 on 2021-09-27 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Lists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.PositiveSmallIntegerField(choices=[(1, 'Szukający'), (2, 'Obrotny')], null=True)),
                ('name', models.CharField(max_length=255, verbose_name='imię')),
                ('surname', models.CharField(max_length=255, verbose_name='nazwisko')),
                ('description', models.TextField(verbose_name='opis')),
                ('profilimg', models.ImageField(blank=True, default='media/1.png', upload_to='media/profiles/')),
                ('kod', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('strona', models.CharField(blank=True, default='np www.mojadomena.pl', max_length=255, null=True)),
                ('telefon', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('profesja', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('miasto', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('port1', models.ImageField(blank=True, default='media/gwiazdka.png', null=True, upload_to='media/portfolio/', verbose_name='galeria zdjęcie nr 1')),
                ('port2', models.ImageField(blank=True, default='media/gwiazdka.png', null=True, upload_to='media/portfolio/', verbose_name='galeria zdjęcie nr 2')),
                ('port3', models.ImageField(blank=True, default='media/gwiazdka.png', null=True, upload_to='media/portfolio/', verbose_name='galeria zdjęcie nr 3')),
                ('port4', models.ImageField(blank=True, default='media/gwiazdka.png', null=True, upload_to='media/portfolio/', verbose_name='galeria zdjęcie nr 4')),
                ('port5', models.ImageField(blank=True, default='media/gwiazdka.png', null=True, upload_to='media/portfolio/', verbose_name='galeria zdjęcie nr 5')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Aktywny'), (2, 'Nieaktywny')], default=1)),
                ('kategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Lists.category', verbose_name='Kategoria')),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
