# Generated by Django 3.2.7 on 2021-10-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_profil_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('Aktywny', 'Aktywny'), ('Nieaktywny', 'Nieaktywny')], default=1),
        ),
    ]
