# Generated by Django 3.2.7 on 2021-10-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_profil_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='status',
            field=models.CharField(choices=[('Aktywny', 'Aktywny'), ('Nieaktywny', 'Nieaktywny')], default='Aktywny', max_length=255),
        ),
    ]
