# Generated by Django 3.2.7 on 2021-10-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_profil_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='black',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
