# Generated by Django 3.2.7 on 2021-10-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_alter_profil_black'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='description',
            field=models.TextField(blank=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='imię'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='surname',
            field=models.CharField(blank=True, max_length=255, verbose_name='nazwisko'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='typ',
            field=models.CharField(blank=True, choices=[('Szukający', 'Szukający'), ('Obrotny', 'Obrotny')], max_length=255, null=True),
        ),
    ]
