# Generated by Django 3.2.7 on 2021-10-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Z kim mamy przyjemność?')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('Problemy Techniczne', 'Problemy Techniczne'), ('Współpraca', 'Współpraca'), ('Promocja i Reklama', 'Promocja i Reklama'), ('Wydarzenia i imprezy', 'Wydarzenia i imprezy')], max_length=255, verbose_name='temat')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('message', models.TextField(verbose_name='Treść wiadomości')),
            ],
        ),
        migrations.CreateModel(
            name='introFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='tytuł')),
                ('zdj', models.ImageField(blank=True, default='media/1.jpg', null=True, upload_to='media/aktualnosci/', verbose_name='aktualnosci1')),
            ],
            options={
                'verbose_name': 'Zdjęcie w intro',
                'verbose_name_plural': 'Zdjęcia w intro',
            },
        ),
    ]
