# Generated by Django 3.2.7 on 2021-09-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0002_alter_city_land'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='profilimg',
            field=models.ImageField(blank=True, default='media/1.png', upload_to='media/kategorie/'),
        ),
    ]
