# Generated by Django 3.2.7 on 2021-09-27 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0003_category_profilimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='profilimg',
            new_name='ikona',
        ),
    ]
