# Generated by Django 3.2.7 on 2021-09-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='tytuł')),
                ('paragraf1', models.TextField()),
                ('paragraf2', models.TextField()),
                ('paragraf3', models.TextField()),
                ('paragraf4', models.TextField()),
                ('paragraf5', models.TextField()),
                ('index', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('fotopress1', models.ImageField(blank=True, upload_to='media/press/')),
                ('fotopress2', models.ImageField(blank=True, upload_to='media/press/')),
                ('fotopress3', models.ImageField(blank=True, upload_to='media/press/')),
                ('fotopress4', models.ImageField(blank=True, upload_to='media/press/')),
                ('fotopress5', models.ImageField(blank=True, upload_to='media/press/')),
            ],
            options={
                'verbose_name': 'Artykuł',
                'verbose_name_plural': 'Artykuły',
            },
        ),
    ]
