# Generated by Django 3.2.7 on 2021-09-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obcpress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='dodany dnia'),
            preserve_default=False,
        ),
    ]
