# Generated by Django 3.2.7 on 2021-09-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obcpress', '0002_articles_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='dodany dnia'),
        ),
    ]
