# Generated by Django 3.2.7 on 2021-09-21 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Obcpress', '0003_alter_articles_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='created_at',
        ),
    ]
