# Generated by Django 3.2.7 on 2021-09-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obcpress', '0004_remove_articles_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='dodany dnia'),
        ),
    ]
